# Modified from https://towardsdatascience.com/how-to-generate-music-using-a-lstm-neural-network-in-keras-68786834d4c5
# Modified by Austin Irvine, ...
# Date: May 2019
# Purpose: Place notes & chords into midi output or song format to export to a midi-player(song creation tool)
from music21 import converter, instrument, note, chord

offset = 0
output_notes = []

# create note and chord objects based on the values generated by the model
def NoteCreation(prediction_output, instrumentType):
    for pattern in prediction_output:
        # pattern is a chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:

                new_note = note.Note(int(current_note))

                if instrumentType == 'piano':
                    new_note.storedInstrument = instrument.Piano()
                elif instrumentType == 'bass':
                    new_note.storedInstrument = instrument.Bass()
                else:
                    new_note.storedInstrument = instrument.Sax()
                
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
        # pattern is a note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset

            if instrumentType == 'piano':
                new_note.storedInstrument = instrument.Piano()
            elif instrumentType == 'bass':
                new_note.storedInstrument = instrument.Bass()
            else:
                new_note.storedInstrument = instrument.Sax()

            output_notes.append(new_note)

        # increase offset each iteration so that notes do not stack
        offset += 0.5

def CreateSong(prediction_output, instrumentType):
    NoteCreation(prediction_output, instrumentType)

    # If sax is our last instrument, this is when we want to output the midi file
    if instrumentType == 'sax':
        midi_stream = stream.Stream(output_notes)
        midi_stream.write('midi', fp='louis_armstrong0.mid')